apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fiverr
  namespace: fiverr
spec:
  dnsNames:
    - fiverr.shujaakbar.com
  secretName: fiverr-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
  